version: '3.8'

services:
  local_mysql:
    image: mysql:8.0
    volumes:
      - ./mysql_container/mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - alfian_network
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  local_postgres:
    image: 'postgres:13'
    volumes:
      - ./postgresql_container/postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - alfian_network
    environment:
      POSTGRES_USER: ${POSTGRES_DWH_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DWH_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DWH_DB}

networks:
  alfian_network:
    driver: bridge
